package com.secondlife.secondlife.common;

import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

public final class PageableUtils {

    private PageableUtils() {}

    /**
     * Sanitizes pageable sort parameters against an allowed whitelist of entity property names.
     * Safely strips bracket/quote artifacts (such as [""] or ["createdAt"] generated by Swagger UI or frontend JSON serialization).
     * Falls back to defaultSort if the provided sort parameters are empty, invalid, or unsorted.
     *
     * @param pageable incoming pageable from request
     * @param allowedProperties set of allowed property names (case-insensitive)
     * @param defaultSort fallback sort to use when sort is empty or invalid
     * @return a safe Pageable instance
     */
    public static Pageable sanitize(Pageable pageable, Set<String> allowedProperties, Sort defaultSort) {
        int pageNumber = pageable != null ? pageable.getPageNumber() : 0;
        int pageSize = pageable != null && pageable.getPageSize() > 0 ? pageable.getPageSize() : 20;

        if (pageable == null || pageable.getSort() == null || pageable.getSort().isUnsorted()) {
            return PageRequest.of(pageNumber, pageSize, defaultSort != null ? defaultSort : Sort.unsorted());
        }

        List<Sort.Order> safeOrders = new ArrayList<>();
        for (Sort.Order order : pageable.getSort()) {
            String property = order.getProperty();
            if (property == null) {
                continue;
            }

            // Strip brackets, quotes, whitespace: e.g. [""] -> "" or ["createdAt"] -> createdAt
            String cleaned = property.replaceAll("[\\[\\]\"']", "").trim();
            if (cleaned.isEmpty()) {
                continue;
            }

            if (allowedProperties != null && !allowedProperties.isEmpty()) {
                for (String allowed : allowedProperties) {
                    if (allowed.equalsIgnoreCase(cleaned)) {
                        safeOrders.add(new Sort.Order(order.getDirection(), allowed));
                        break;
                    }
                }
            } else {
                safeOrders.add(new Sort.Order(order.getDirection(), cleaned));
            }
        }

        Sort finalSort = safeOrders.isEmpty()
                ? (defaultSort != null ? defaultSort : Sort.unsorted())
                : Sort.by(safeOrders);

        return PageRequest.of(pageNumber, pageSize, finalSort);
    }
}
