package com.secondlife.secondlife.enums;

public enum PermissionCode {
    PROFILE_READ_SELF,
    PROFILE_UPDATE_SELF,
    PASSWORD_CHANGE_SELF,
    SELLER_VERIFICATION_SUBMIT,
    SELLER_VERIFICATION_READ_SELF,
    USER_READ_ANY,
    USER_STATUS_UPDATE,
    SELLER_VERIFICATION_READ_ANY,
    SELLER_VERIFICATION_REVIEW,
    INSPECTION_CENTER_ACCOUNT_MANAGE,
    ROLE_READ,
    POST_CREATE,
    POST_UPDATE,
    POST_DELETE
}
