package com.secondlife.secondlife.enums;

public enum PermissionCode {
    PROFILE_READ_SELF,
    PROFILE_UPDATE_SELF,
    PASSWORD_CHANGE_SELF,
    SELLER_VERIFICATION_SUBMIT,
    SELLER_VERIFICATION_READ_SELF,
    LISTING_CREATE_SELF,
    LISTING_PUBLISH_SELF,
    LISTING_VALUATION_SELF,
    CREDIT_READ_SELF,
    CREDIT_PURCHASE_SELF,
    INSPECTION_REPORT_SUBMIT,
    STAFF_LISTING_REVIEW,
    STAFF_FRAUD_REVIEW,
    STAFF_DISPUTE_REVIEW,
    STAFF_PAYOUT_REVIEW,
    STAFF_PAYOUT_HOLD,
    STAFF_USER_WARN,
    STAFF_USER_TEMP_RESTRICT,
    ADMIN_STAFF_MANAGE,
    ADMIN_RBAC_MANAGE,
    ADMIN_PRICING_MANAGE,
    ADMIN_COMMISSION_MANAGE,
    ADMIN_CONFIG_MANAGE,
    ADMIN_CATALOG_MANAGE,
    ADMIN_PERMANENT_BAN,
    ADMIN_HIGH_VALUE_PAYOUT,
    USER_READ_ANY,
    USER_STATUS_UPDATE,
    SELLER_VERIFICATION_READ_ANY,
    SELLER_VERIFICATION_REVIEW,
    POST_REVIEW,
    INSPECTION_CENTER_ACCOUNT_MANAGE,
    ROLE_READ,
    POST_CREATE,
    POST_UPDATE,
    POST_DELETE,
    INSPECTION_ORDER_READ_SELF,
    INSPECTION_ORDER_READ_ANY,
    INSPECTION_ORDER_ASSIGN,
    INSPECTION_STAFF_MANAGE,
    AI_CHAT_SELF,
    MEDIA_UPLOAD_SELF;

    /** Only permissions backed by implemented API operations can be initialized through the catalog API. */
    public boolean isImplemented() {
        return switch (this) {
            case PROFILE_READ_SELF, PROFILE_UPDATE_SELF, PASSWORD_CHANGE_SELF,
                 SELLER_VERIFICATION_SUBMIT, SELLER_VERIFICATION_READ_SELF,
                 LISTING_CREATE_SELF, LISTING_PUBLISH_SELF, LISTING_VALUATION_SELF, CREDIT_READ_SELF, CREDIT_PURCHASE_SELF,
                 INSPECTION_REPORT_SUBMIT, ADMIN_RBAC_MANAGE, ADMIN_PRICING_MANAGE, ADMIN_CATALOG_MANAGE, STAFF_LISTING_REVIEW,
                 USER_READ_ANY, USER_STATUS_UPDATE, SELLER_VERIFICATION_READ_ANY,
                 SELLER_VERIFICATION_REVIEW, POST_REVIEW, INSPECTION_CENTER_ACCOUNT_MANAGE,
                 INSPECTION_ORDER_READ_SELF, INSPECTION_ORDER_READ_ANY,
                 INSPECTION_ORDER_ASSIGN, INSPECTION_STAFF_MANAGE, AI_CHAT_SELF, MEDIA_UPLOAD_SELF -> true;
            default -> false;
        };
    }
}
