UPDATE items SET name = 'Sofa / Ghế dài' WHERE seed_key = 'living-room/sofa';
UPDATE items SET name = 'Máy sấy' WHERE seed_key = 'balcony-laundry/clothes-dryer';
UPDATE items SET name = 'Máy nước nóng' WHERE seed_key = 'bathroom/water-heater';
UPDATE items SET name = 'Quạt máy' WHERE seed_key = 'other/fan';
UPDATE items SET name = 'Kệ Tivi' WHERE seed_key = 'living-room/tv-stand';
UPDATE items SET name = 'Lò vi sóng / Lò nướng' WHERE seed_key = 'kitchen/microwave-oven';
UPDATE items SET name = 'Tủ quần áo' WHERE seed_key = 'bedroom/wardrobe';
UPDATE items SET name = 'Máy giặt' WHERE seed_key = 'balcony-laundry/washing-machine';
UPDATE items SET name = 'Tủ / Kệ phòng tắm' WHERE seed_key = 'bathroom/bathroom-cabinet';
UPDATE items SET name = 'Bếp từ / Bếp hồng ngoại' WHERE seed_key = 'kitchen/induction-cooker';
UPDATE items SET name = 'Khung giường' WHERE seed_key = 'bedroom/bed-frame';
UPDATE items SET name = 'Nồi cơm điện' WHERE seed_key = 'kitchen/rice-cooker';
UPDATE items SET name = 'Nệm / Đệm' WHERE seed_key = 'bedroom/mattress';
UPDATE items SET name = 'Tủ lạnh' WHERE seed_key = 'kitchen/refrigerator';
UPDATE items SET name = 'Tủ đầu giường' WHERE seed_key = 'bedroom/bedside-table';
UPDATE items SET name = 'Bàn làm việc' WHERE seed_key = 'bedroom/desk';
UPDATE items SET name = 'Hộp đồ nghề' WHERE seed_key = 'other/tool-box';
UPDATE items SET name = 'Bồn rửa mặt' WHERE seed_key = 'bathroom/washbasin';
UPDATE items SET name = 'Đèn đứng' WHERE seed_key = 'living-room/floor-lamp';
UPDATE items SET name = 'Tủ đựng đồ' WHERE seed_key = 'other/storage-cabinet';
UPDATE items SET name = 'Máy lọc không khí' WHERE seed_key = 'other/air-purifier';
UPDATE items SET name = 'Giỏ đựng đồ giặt' WHERE seed_key = 'balcony-laundry/laundry-basket';
UPDATE items SET name = 'Bàn trang điểm' WHERE seed_key = 'bedroom/dressing-table';
UPDATE items SET name = 'Bàn ăn' WHERE seed_key = 'kitchen/dining-table';
UPDATE items SET name = 'Bàn ban công' WHERE seed_key = 'balcony-laundry/balcony-table';
UPDATE items SET name = 'Bồn cầu' WHERE seed_key = 'bathroom/toilet';
UPDATE items SET name = 'Bàn ủi / Bàn là' WHERE seed_key = 'balcony-laundry/iron';
UPDATE items SET name = 'Giá phơi đồ' WHERE seed_key = 'balcony-laundry/drying-rack';
UPDATE items SET name = 'Giá sách / Kệ sách' WHERE seed_key = 'living-room/bookshelf';
UPDATE items SET name = 'Máy xay sinh tố' WHERE seed_key = 'kitchen/blender';
UPDATE items SET name = 'Gương' WHERE seed_key = 'bathroom/mirror';
UPDATE items SET name = 'Vòi hoa sen' WHERE seed_key = 'bathroom/shower-set';
UPDATE items SET name = 'Bàn trà / Bàn sofa' WHERE seed_key = 'living-room/coffee-table';
UPDATE items SET name = 'Ghế bành' WHERE seed_key = 'living-room/armchair';
UPDATE items SET name = 'Kệ để giày' WHERE seed_key = 'other/shoe-rack';
UPDATE items SET name = 'Máy hút bụi' WHERE seed_key = 'other/vacuum-cleaner';