-- Hibernate created enum CHECK constraints on existing PostgreSQL databases.
-- Its schema update does not expand those constraints when Java enum values change.
-- Replace them after adding VNPT reason codes and the retry audit event.

ALTER TABLE seller_verifications
    DROP CONSTRAINT IF EXISTS seller_verifications_reason_code_check;

ALTER TABLE seller_verifications
    ADD CONSTRAINT seller_verifications_reason_code_check CHECK (reason_code IN (
        'DOCUMENT_EXPIRED', 'DOCUMENT_SUSPECTED_FAKE', 'FACE_MISMATCH',
        'LIVENESS_FAILED', 'UNSUPPORTED_DOCUMENT', 'CONFIRMED_IDENTITY_MISMATCH',
        'EKYC_CONTEXT_MISSING', 'IMAGE_TOO_BLURRY', 'IMAGE_NOT_ACCESSIBLE',
        'IMAGE_GLARE', 'DOCUMENT_NOT_FULLY_VISIBLE', 'SELFIE_QUALITY_LOW',
        'OCR_LOW_CONFIDENCE_DUE_TO_IMAGE', 'OCR_LOW_CONFIDENCE',
        'FACE_MATCH_BORDERLINE', 'DOCUMENT_DATA_INCONSISTENCY', 'OCR_INCONSISTENT',
        'PROVIDER_MANUAL_REVIEW_REQUIRED', 'DUPLICATE_IDENTITY_EXCEPTION',
        'AMBIGUOUS_IDENTITY_RESULT', 'PROVIDER_TIMEOUT', 'PROVIDER_UNAVAILABLE',
        'PROVIDER_AUTH_FAILED', 'PROVIDER_REQUEST_REJECTED', 'DUPLICATE_IDENTITY',
        'ACCOUNT_LOCKED', 'ACCOUNT_DISABLED', 'PERMANENT_SELLER_BAN',
        'REPEATED_EKYC_FAILURES', 'RISK_FLAGGED', 'MANUAL_REVIEW_REQUIRED', 'NONE'
    ));

ALTER TABLE seller_verification_events
    DROP CONSTRAINT IF EXISTS seller_verification_events_reason_code_check;

ALTER TABLE seller_verification_events
    ADD CONSTRAINT seller_verification_events_reason_code_check CHECK (reason_code IN (
        'DOCUMENT_EXPIRED', 'DOCUMENT_SUSPECTED_FAKE', 'FACE_MISMATCH',
        'LIVENESS_FAILED', 'UNSUPPORTED_DOCUMENT', 'CONFIRMED_IDENTITY_MISMATCH',
        'EKYC_CONTEXT_MISSING', 'IMAGE_TOO_BLURRY', 'IMAGE_NOT_ACCESSIBLE',
        'IMAGE_GLARE', 'DOCUMENT_NOT_FULLY_VISIBLE', 'SELFIE_QUALITY_LOW',
        'OCR_LOW_CONFIDENCE_DUE_TO_IMAGE', 'OCR_LOW_CONFIDENCE',
        'FACE_MATCH_BORDERLINE', 'DOCUMENT_DATA_INCONSISTENCY', 'OCR_INCONSISTENT',
        'PROVIDER_MANUAL_REVIEW_REQUIRED', 'DUPLICATE_IDENTITY_EXCEPTION',
        'AMBIGUOUS_IDENTITY_RESULT', 'PROVIDER_TIMEOUT', 'PROVIDER_UNAVAILABLE',
        'PROVIDER_AUTH_FAILED', 'PROVIDER_REQUEST_REJECTED', 'DUPLICATE_IDENTITY',
        'ACCOUNT_LOCKED', 'ACCOUNT_DISABLED', 'PERMANENT_SELLER_BAN',
        'REPEATED_EKYC_FAILURES', 'RISK_FLAGGED', 'MANUAL_REVIEW_REQUIRED', 'NONE'
    ));

ALTER TABLE seller_verification_events
    DROP CONSTRAINT IF EXISTS seller_verification_events_event_type_check;

ALTER TABLE seller_verification_events
    ADD CONSTRAINT seller_verification_events_event_type_check CHECK (event_type IN (
        'SUBMITTED', 'EKYC_STARTED', 'EKYC_RETRY_REQUESTED', 'EKYC_PASSED',
        'EKYC_FAILED', 'RESUBMISSION_REQUIRED', 'RISK_REVIEW_REQUIRED',
        'SYSTEM_APPROVED', 'SYSTEM_REJECTED', 'ADMIN_APPROVED', 'ADMIN_REJECTED'
    ));
