ALTER TABLE user_profiles
ADD COLUMN province VARCHAR(255),
ADD COLUMN district VARCHAR(255),
ADD COLUMN ward VARCHAR(255),
ADD COLUMN street_address VARCHAR(255),
ADD COLUMN latitude DOUBLE PRECISION,
ADD COLUMN longitude DOUBLE PRECISION;
